### ISSUE TITLE
Can I use the common "Share icon" instead of the button text and font-awesome icon showed in the demo?

### ISSUE THREAD

**Issue by Nazarah** [carrot/share-button#316]
## Details
![share-button](https://cloud.githubusercontent.com/assets/17976243/24034844/a3847e42-0afb-11e7-9c40-f2f484c2852d.png)

This one is more intuitive and common among people.
Got this from Android material Design icon set.

**Comment by refi64** [comment]
FWIW this is untested, but you *should* be able to shove this in your CSS:

```css
share-button:before {
  background: url("URL-TO-MY-ICON.svg");
}
```

and then create a `ShareButton` using this:

```javascript
new ShareButton({ui: { buttonText: '' }});
```
